image:
  file: .gitpod.Dockerfile

tasks:
  - name: Maven clean install
    init: mvn clean install
    command: mvn spring-boot:run


ports:
  - port: 8080
    onOpen: open-preview


vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot

github:
  prebuilds:
    main: true
    pullRequests: true
    addCheck: true
    addComment: false
